In [2]:
import numpy as np

In [8]:
a=np.arange(10,22).reshape(3,4)
print(a)
print(a.ravel()) #this function create any dimension array into 1d array
print(a)
print()
print(a.transpose())

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13 14 15 16 17 18 19 20 21]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[10 14 18]
 [11 15 19]
 [12 16 20]
 [13 17 21]]


In [14]:
arr1=np.arange(1,9).reshape(4,2)
print(arr1)
arr2=np.arange(1,9).reshape(4,2)
print(arr1)
print()
print(np.hstack((arr1,arr2)))
print()
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]
 [7 8 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
arr3=np.random.randint(1,100,20).reshape(5,4)
print(arr3)
# to filter something from array we call it as BOOLEAN INDEXING
print(arr3[arr3>30])


[[79 14  8  1]
 [68 99 30 75]
 [16 39 46 45]
 [80 23 27 82]
 [81 14 79 24]]
[79 68 99 75 39 46 45 80 82 81 79]
