### array creation

In [3]:
import numpy as np

In [5]:
arr1=np.array([2,"j"])
print(arr1)

['2' 'j']


In [6]:
arr2=np.array([[1,2],[2,3]])
print(arr2)

[[1 2]
 [2 3]]


In [8]:
arr3=np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr4=np.ones((2,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr5=np.identity(5)
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
print(np.arange(5,10))

[5 6 7 8 9]


In [4]:
arr9=np.linspace(10,20,15)
print(arr9)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]


In [9]:
arr0=arr9.copy()
print(arr0)
print(np.ndim(arr0))
arr0.shape
arr0.ndim

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]
1


1

In [18]:
arr3=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.dtype)
print(arr3.astype('float'))

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
3
8
int64
[[[1. 2.]
  [3. 4.]]

 [[4. 5.]
  [6. 7.]]]


In [30]:
ar=np.arange(24).reshape(6,4)
print(ar)
print()
print(ar[:,2])
print(ar[2:4,1:3])
print(ar[4:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[ 2  6 10 14 18 22]
[[ 9 10]
 [13 14]]
[[18 19]
 [22 23]]


In [32]:
ar=np.arange(24).reshape(6,4)
for i in ar:
    print(i)
for i in np.nditer(ar):
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## operations on array

In [43]:
arr1=np.arange(20,30).reshape(2,5)
print(arr1)
arr2=np.arange(10,20).reshape(2,5)
print(arr2)
print (arr1-arr2)

print(arr1>25)

print(arr1* arr2)
print(arr1*2)
print(arr1.max())
print(arr1.min())

[[20 21 22 23 24]
 [25 26 27 28 29]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[[False False False False False]
 [False  True  True  True  True]]
[[200 231 264 299 336]
 [375 416 459 504 551]]
[[40 42 44 46 48]
 [50 52 54 56 58]]
29
20


In [51]:
a=np.array([[1,2,3],[4,5,6]])
# b=np.array([[7,8,9],[10,12,14]])
b=np.arange(7,13).reshape(3,2)
print(a.dot(b))
print(a)
print()
print(a.max(axis=0))
print()
print(a.max(axis=1))

[[ 58  64]
 [139 154]]
[[1 2 3]
 [4 5 6]]

[4 5 6]

[3 6]


In [59]:
arr4=np.arange(10,20)
print(arr4.mean())
print(np.mean(arr4))
print(arr4.std())


14.5
14.5
2.8722813232690143
